apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim-todo
  labels:
    app: postgres-todo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
